export const AuthContent = {
  signin_title: "تسجيل الدخول",
  signin_subtitle: "مرحباً بعودتك إلى Centre.com.pk",
  signin_button: "تسجيل الدخول",
  signing_in: "جاري تسجيل الدخول...",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  no_account: "ليس لديك حساب؟",
  signup_link: "إنشاء حساب",
  forgot_password: "نسيت كلمة المرور؟",
  signin_success: "تم تسجيل الدخول بنجاح!",
  invalid_credentials: "بريد إلكتروني أو كلمة مرور غير صالحة",
  account_unverified: "يرجى التحقق من بريدك الإلكتروني أولاً",
  
  signup_title: "إنشاء حساب",
  signup_subtitle: "أنشئ حسابك المجاني",
  signup_button: "إنشاء حساب",
  creating: "جاري إنشاء الحساب...",
  name: "الاسم",
  have_account: "لديك حساب بالفعل؟",
  signin_link: "تسجيل الدخول",
  check_email: "تحقق من بريدك الإلكتروني",
  verification_sent: "أرسلنا رابط التحقق إلى",
  check_inbox: "يرجى التحقق من صندوق الوارد",
  no_email: "لم تصلك الرسالة؟ تحقق من مجلد البريد العشوائي",
  resend: "إعادة إرسال التحقق",
  go_signin: "اذهب إلى تسجيل الدخول →",
  registration_success: "تم التسجيل بنجاح!",
  email_exists: "البريد الإلكتروني مسجل بالفعل",
  password_length: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
  
  forgot_title: "نسيت كلمة المرور",
  forgot_subtitle: "أدخل بريدك الإلكتروني لاستلام رابط إعادة التعيين",
  send_link: "إرسال رابط التعيين",
  sending: "جاري الإرسال...",
  back_signin: "العودة إلى تسجيل الدخول",
  check_email_reset: "إذا كان الحساب موجوداً، ستتلقى رابط إعادة التعيين.",
  
  reset_title: "إعادة تعيين كلمة المرور",
  reset_subtitle: "أدخل كلمة المرور الجديدة",
  reset_button: "إعادة تعيين",
  resetting: "جاري إعادة التعيين...",
  new_password: "كلمة مرور جديدة",
  confirm_password: "تأكيد كلمة المرور",
  passwords_dont_match: "كلمات المرور غير متطابقة",
  password_reset_success: "تم إعادة تعيين كلمة المرور بنجاح!",
  invalid_token: "رابط إعادة تعيين غير صالح أو منتهي",
  
  verify_title: "التحقق من البريد",
  verifying: "جاري التحقق من بريدك الإلكتروني...",
  verified: "تم التحقق! ✅",
  verification_failed: "فشل التحقق",
  redirecting_signin: "جاري التحويل إلى تسجيل الدخول...",
  signin_now: "تسجيل الدخول الآن →",
  signup_again: "إنشاء حساب مرة أخرى",
  go_home: "الصفحة الرئيسية",
};
