export const AuthContent = {
  signin_title: "Sign In",
  signin_subtitle: "Welcome back to Centre.com.pk",
  signin_button: "Sign In",
  signing_in: "Signing in...",
  email: "Email",
  password: "Password",
  no_account: "Don't have an account?",
  signup_link: "Sign Up",
  forgot_password: "Forgot password?",
  signin_success: "Signed in successfully!",
  invalid_credentials: "Invalid email or password",
  account_unverified: "Please verify your email first",
  
  signup_title: "Sign Up",
  signup_subtitle: "Create your free account",
  signup_button: "Create Account",
  creating: "Creating account...",
  name: "Name",
  have_account: "Already have an account?",
  signin_link: "Sign In",
  check_email: "Check Your Email",
  verification_sent: "We sent a verification link to",
  check_inbox: "Please check your inbox and click the link to verify your account.",
  no_email: "Didn't receive the email? Check spam folder or",
  resend: "resend verification",
  go_signin: "Go to Sign In →",
  registration_success: "Registration successful!",
  email_exists: "Email already registered",
  password_length: "Password must be at least 8 characters",
  
  forgot_title: "Forgot Password",
  forgot_subtitle: "Enter your email to receive a reset link",
  send_link: "Send Reset Link",
  sending: "Sending...",
  back_signin: "Back to Sign In",
  check_email_reset: "If an account exists, you will receive a reset link.",
  
  reset_title: "Reset Password",
  reset_subtitle: "Enter your new password",
  reset_button: "Reset Password",
  resetting: "Resetting...",
  new_password: "New Password",
  confirm_password: "Confirm Password",
  passwords_dont_match: "Passwords do not match",
  password_reset_success: "Password reset successful!",
  invalid_token: "Invalid or expired reset link",
  
  verify_title: "Verify Email",
  verifying: "Verifying your email...",
  verified: "Email Verified! ✅",
  verification_failed: "Verification Failed",
  redirecting_signin: "Redirecting to sign in...",
  signin_now: "Sign In Now →",
  signup_again: "Sign Up Again",
  go_home: "Go Home",
};
