export const AuthContent = {
  signin_title: "साइन इन",
  signin_subtitle: "Centre.com.pk में आपका स्वागत है",
  signin_button: "साइन इन",
  signing_in: "साइन इन हो रहा है...",
  email: "ईमेल",
  password: "पासवर्ड",
  no_account: "खाता नहीं है?",
  signup_link: "साइन अप",
  forgot_password: "पासवर्ड भूल गए?",
  signin_success: "सफलतापूर्वक साइन इन!",
  invalid_credentials: "गलत ईमेल या पासवर्ड",
  account_unverified: "कृपया पहले अपना ईमेल सत्यापित करें",
  
  signup_title: "साइन अप",
  signup_subtitle: "अपना मुफ्त खाता बनाएं",
  signup_button: "खाता बनाएं",
  creating: "खाता बन रहा है...",
  name: "नाम",
  have_account: "पहले से खाता है?",
  signin_link: "साइन इन",
  check_email: "अपना ईमेल देखें",
  verification_sent: "हमने सत्यापन लिंक भेजा है",
  check_inbox: "कृपया अपना इनबॉक्स देखें",
  no_email: "ईमेल नहीं मिला? स्पैम फोल्डर देखें",
  resend: "पुनः सत्यापन भेजें",
  go_signin: "साइन इन पर जाएं →",
  registration_success: "पंजीकरण सफल!",
  email_exists: "ईमेल पहले से पंजीकृत है",
  password_length: "पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
  
  forgot_title: "पासवर्ड भूल गए",
  forgot_subtitle: "रीसेट लिंक पाने के लिए ईमेल दर्ज करें",
  send_link: "रीसेट लिंक भेजें",
  sending: "भेजा जा रहा है...",
  back_signin: "वापस साइन इन पर",
  check_email_reset: "यदि खाता मौजूद है तो आपको रीसेट लिंक मिलेगा।",
  
  reset_title: "पासवर्ड रीसेट",
  reset_subtitle: "अपना नया पासवर्ड दर्ज करें",
  reset_button: "पासवर्ड रीसेट",
  resetting: "रीसेट हो रहा है...",
  new_password: "नया पासवर्ड",
  confirm_password: "पासवर्ड की पुष्टि करें",
  passwords_dont_match: "पासवर्ड मेल नहीं खाते",
  password_reset_success: "पासवर्ड सफलतापूर्वक रीसेट!",
  invalid_token: "अमान्य या समाप्त रीसेट लिंक",
  
  verify_title: "ईमेल सत्यापन",
  verifying: "आपका ईमेल सत्यापित हो रहा है...",
  verified: "ईमेल सत्यापित! ✅",
  verification_failed: "सत्यापन विफल",
  redirecting_signin: "साइन इन पर रीडायरेक्ट...",
  signin_now: "अभी साइन इन करें →",
  signup_again: "फिर से साइन अप करें",
  go_home: "होम पेज",
};
