export const AuthContent = {
  signin_title: "سائن ان",
  signin_subtitle: "Centre.com.pk میں دوبارہ خوش آمدید",
  signin_button: "سائن ان",
  signing_in: "سائن ان ہو رہا ہے...",
  email: "ای میل",
  password: "پاسورڈ",
  no_account: "اکاؤنٹ نہیں ہے؟",
  signup_link: "سائن اپ",
  forgot_password: "پاسورڈ بھول گئے؟",
  signin_success: "کامیابی سے سائن ان!",
  invalid_credentials: "غلط ای میل یا پاسورڈ",
  account_unverified: "براہ کرم پہلے اپنا ای میل تصدیق کریں",
  
  signup_title: "سائن اپ",
  signup_subtitle: "اپنا مفت اکاؤنٹ بنائیں",
  signup_button: "اکاؤنٹ بنائیں",
  creating: "اکاؤنٹ بن رہا ہے...",
  name: "نام",
  have_account: "پہلے سے اکاؤنٹ ہے؟",
  signin_link: "سائن ان",
  check_email: "اپنا ای میل چیک کریں",
  verification_sent: "ہم نے تصدیقی لنک بھیجا ہے",
  check_inbox: "براہ کرم اپنا ان باکس چیک کریں",
  no_email: "ای میل نہیں ملی؟ سپیم فولڈر چیک کریں",
  resend: "دوبارہ تصدیق بھیجیں",
  go_signin: "سائن ان پر جائیں →",
  registration_success: "رجسٹریشن کامیاب!",
  email_exists: "ای میل پہلے سے رجسٹرڈ ہے",
  password_length: "پاسورڈ کم از کم 8 حروف کا ہونا چاہیے",
  
  forgot_title: "پاسورڈ بھول گئے",
  forgot_subtitle: "ری سیٹ لنک حاصل کرنے کے لیے ای میل درج کریں",
  send_link: "ری سیٹ لنک بھیجیں",
  sending: "بھیجا جا رہا ہے...",
  back_signin: "واپس سائن ان پر",
  check_email_reset: "اگر اکاؤنٹ موجود ہے تو آپ کو ری سیٹ لنک ملے گا۔",
  
  reset_title: "پاسورڈ ری سیٹ",
  reset_subtitle: "اپنا نیا پاسورڈ درج کریں",
  reset_button: "پاسورڈ ری سیٹ",
  resetting: "ری سیٹ ہو رہا ہے...",
  new_password: "نیا پاسورڈ",
  confirm_password: "پاسورڈ کی تصدیق کریں",
  passwords_dont_match: "پاسورڈ مماثل نہیں",
  password_reset_success: "پاسورڈ کامیابی سے ری سیٹ!",
  invalid_token: "غلط یا ختم شدہ ری سیٹ لنک",
  
  verify_title: "ای میل تصدیق",
  verifying: "آپ کے ای میل کی تصدیق ہو رہی ہے...",
  verified: "ای میل تصدیق شدہ! ✅",
  verification_failed: "تصدیق ناکام",
  redirecting_signin: "سائن ان پر ری ڈائریکٹ کیا جا رہا ہے...",
  signin_now: "ابھی سائن ان کریں →",
  signup_again: "دوبارہ سائن اپ کریں",
  go_home: "ہوم پیج",
};
