export const dashboardContent = {
  ar: {
    title: 'لوحة التحكم',
    subtitle: 'إدارة مستنداتك ومحتواك',
    newDocument: 'مستند جديد',
    myDocuments: 'مستنداتي',
    sharedWithMe: 'تمت مشاركتها معي',
    templates: 'القوالب',
    trash: 'المحذوفات',
    editor: {
      title: 'محرر المستندات',
      untitled: 'مستند بدون عنوان',
      save: 'حفظ',
      saving: 'جاري الحفظ...',
      saved: 'تم الحفظ',
      autoSave: 'حفظ تلقائي',
      lastSaved: 'آخر حفظ',
      export: 'تصدير',
      exportPDF: 'تصدير كـ PDF',
      exportHTML: 'تصدير كـ HTML',
      exportMarkdown: 'تصدير كـ Markdown',
      share: 'مشاركة',
      copyLink: 'نسخ الرابط',
      makePublic: 'جعله عاماً',
      wordCount: 'كلمات',
      charCount: 'حروف',
      readingTime: 'دقائق قراءة',
      fullscreen: 'ملء الشاشة',
      exitFullscreen: 'الخروج من ملء الشاشة',
      undo: 'تراجع',
      redo: 'إعادة',
      delete: 'حذف المستند',
      confirmDelete: 'هل أنت متأكد من حذف هذا المستند؟',
      noDocuments: 'لا توجد مستندات بعد. أنشئ أول مستند!',
      searchDocuments: 'البحث في المستندات...',
    },
    sidebar: {
      allDocuments: 'جميع المستندات',
      recentDocuments: 'الأخيرة',
      starredDocuments: 'المفضلة',
      folders: 'المجلدات',
      newFolder: 'مجلد جديد',
    },
    templates: {
      blank: 'مستند فارغ',
      meetingNotes: 'ملاحظات الاجتماع',
      blogPost: 'مقالة مدونة',
      projectPlan: 'خطة المشروع',
      personalJournal: 'يوميات شخصية',
    },
    errors: {
      loadFailed: 'فشل تحميل المستندات',
      saveFailed: 'فشل حفظ المستند',
      deleteFailed: 'فشل حذف المستند',
      notFound: 'المستند غير موجود',
      unauthorized: 'يرجى تسجيل الدخول للوصول إلى لوحة التحكم',
    }
  }
};
