export const dashboardContent = {
  en: {
    title: 'Dashboard',
    subtitle: 'Manage your documents and content',
    newDocument: 'New Document',
    myDocuments: 'My Documents',
    sharedWithMe: 'Shared with Me',
    templates: 'Templates',
    trash: 'Trash',
    editor: {
      title: 'Document Editor',
      untitled: 'Untitled Document',
      save: 'Save',
      saving: 'Saving...',
      saved: 'Saved',
      autoSave: 'Auto-save',
      lastSaved: 'Last saved',
      export: 'Export',
      exportPDF: 'Export as PDF',
      exportHTML: 'Export as HTML',
      exportMarkdown: 'Export as Markdown',
      share: 'Share',
      copyLink: 'Copy Link',
      makePublic: 'Make Public',
      wordCount: 'Words',
      charCount: 'Characters',
      readingTime: 'min read',
      fullscreen: 'Fullscreen',
      exitFullscreen: 'Exit Fullscreen',
      undo: 'Undo',
      redo: 'Redo',
      delete: 'Delete Document',
      confirmDelete: 'Are you sure you want to delete this document?',
      noDocuments: 'No documents yet. Create your first one!',
      searchDocuments: 'Search documents...',
    },
    sidebar: {
      allDocuments: 'All Documents',
      recentDocuments: 'Recent',
      starredDocuments: 'Starred',
      folders: 'Folders',
      newFolder: 'New Folder',
    },
    templates: {
      blank: 'Blank Document',
      meetingNotes: 'Meeting Notes',
      blogPost: 'Blog Post',
      projectPlan: 'Project Plan',
      personalJournal: 'Personal Journal',
    },
    errors: {
      loadFailed: 'Failed to load documents',
      saveFailed: 'Failed to save document',
      deleteFailed: 'Failed to delete document',
      notFound: 'Document not found',
      unauthorized: 'Please login to access dashboard',
    }
  }
};
