export const dashboardContent = {
  hi: {
    title: 'डैशबोर्ड',
    subtitle: 'अपने दस्तावेज़ और सामग्री प्रबंधित करें',
    newDocument: 'नया दस्तावेज़',
    myDocuments: 'मेरे दस्तावेज़',
    sharedWithMe: 'मेरे साथ साझा',
    templates: 'टेम्पलेट्स',
    trash: 'ट्रैश',
    editor: {
      title: 'दस्तावेज़ एडिटर',
      untitled: 'शीर्षकहीन दस्तावेज़',
      save: 'सहेजें',
      saving: 'सहेजा जा रहा है...',
      saved: 'सहेजा गया',
      autoSave: 'स्वतः सहेजें',
      lastSaved: 'अंतिम बार सहेजा गया',
      export: 'निर्यात करें',
      exportPDF: 'PDF के रूप में निर्यात करें',
      exportHTML: 'HTML के रूप में निर्यात करें',
      exportMarkdown: 'Markdown के रूप में निर्यात करें',
      share: 'साझा करें',
      copyLink: 'लिंक कॉपी करें',
      makePublic: 'सार्वजनिक करें',
      wordCount: 'शब्द',
      charCount: 'अक्षर',
      readingTime: 'मिनट पढ़ाई',
      fullscreen: 'फुलस्क्रीन',
      exitFullscreen: 'फुलस्क्रीन से बाहर',
      undo: 'पूर्ववत',
      redo: 'पुनः करें',
      delete: 'दस्तावेज़ हटाएं',
      confirmDelete: 'क्या आप वाकई इस दस्तावेज़ को हटाना चाहते हैं?',
      noDocuments: 'अभी तक कोई दस्तावेज़ नहीं। अपना पहला बनाएं!',
      searchDocuments: 'दस्तावेज़ खोजें...',
    },
    sidebar: {
      allDocuments: 'सभी दस्तावेज़',
      recentDocuments: 'हाल के',
      starredDocuments: 'स्टार किए हुए',
      folders: 'फ़ोल्डर्स',
      newFolder: 'नया फ़ोल्डर',
    },
    templates: {
      blank: 'खाली दस्तावेज़',
      meetingNotes: 'मीटिंग नोट्स',
      blogPost: 'ब्लॉग पोस्ट',
      projectPlan: 'प्रोजेक्ट प्लान',
      personalJournal: 'व्यक्तिगत डायरी',
    },
    errors: {
      loadFailed: 'दस्तावेज़ लोड करने में विफल',
      saveFailed: 'दस्तावेज़ सहेजने में विफल',
      deleteFailed: 'दस्तावेज़ हटाने में विफल',
      notFound: 'दस्तावेज़ नहीं मिला',
      unauthorized: 'डैशबोर्ड तक पहुंचने के लिए लॉगिन करें',
    }
  }
};
