export const dashboardContent = {
  ur: {
    title: 'ڈیش بورڈ',
    subtitle: 'اپنے دستاویزات اور مواد کا نظم کریں',
    newDocument: 'نیا دستاویز',
    myDocuments: 'میرے دستاویزات',
    sharedWithMe: 'میرے ساتھ شیئر کردہ',
    templates: 'سانچے',
    trash: 'ردی کی ٹوکری',
    editor: {
      title: 'دستاویز ایڈیٹر',
      untitled: 'بے عنوان دستاویز',
      save: 'محفوظ کریں',
      saving: 'محفوظ ہو رہا ہے...',
      saved: 'محفوظ ہو گیا',
      autoSave: 'خودکار محفوظ',
      lastSaved: 'آخری بار محفوظ',
      export: 'برآمد کریں',
      exportPDF: 'PDF کے طور پر برآمد کریں',
      exportHTML: 'HTML کے طور پر برآمد کریں',
      exportMarkdown: 'Markdown کے طور پر برآمد کریں',
      share: 'شیئر کریں',
      copyLink: 'لنک کاپی کریں',
      makePublic: 'عام کریں',
      wordCount: 'الفاظ',
      charCount: 'حروف',
      readingTime: 'منٹ پڑھائی',
      fullscreen: 'فل سکرین',
      exitFullscreen: 'فل سکرین سے باہر',
      undo: 'واپس',
      redo: 'دوبارہ',
      delete: 'دستاویز حذف کریں',
      confirmDelete: 'کیا آپ واقعی اس دستاویز کو حذف کرنا چاہتے ہیں؟',
      noDocuments: 'ابھی تک کوئی دستاویز نہیں۔ اپنا پہلا بنائیں!',
      searchDocuments: 'دستاویزات تلاش کریں...',
    },
    sidebar: {
      allDocuments: 'تمام دستاویزات',
      recentDocuments: 'حالیہ',
      starredDocuments: 'ستارہ دار',
      folders: 'فولڈرز',
      newFolder: 'نیا فولڈر',
    },
    templates: {
      blank: 'خالی دستاویز',
      meetingNotes: 'میٹنگ نوٹس',
      blogPost: 'بلاگ پوسٹ',
      projectPlan: 'پروجیکٹ پلان',
      personalJournal: 'ذاتی ڈائری',
    },
    errors: {
      loadFailed: 'دستاویزات لوڈ کرنے میں ناکام',
      saveFailed: 'دستاویز محفوظ کرنے میں ناکام',
      deleteFailed: 'دستاویز حذف کرنے میں ناکام',
      notFound: 'دستاویز نہیں ملی',
      unauthorized: 'ڈیش بورڈ تک رسائی کے لیے لاگ ان کریں',
    }
  }
};
