DELETE FROM blog_posts WHERE slug IN (
'javascript-formatter-complete-guide','xml-formatter-complete-guide','url-encoder-complete-guide','base64-encoder-complete-guide',
'color-picker-complete-guide','background-remover-complete-guide','favicon-generator-complete-guide','image-converter-complete-guide',
'image-cropper-complete-guide','image-filters-complete-guide','image-resizer-complete-guide','image-rotator-complete-guide',
'meme-generator-complete-guide','photo-collage-complete-guide','pdf-compressor-complete-guide','pdf-merger-complete-guide',
'pdf-splitter-complete-guide','pdf-to-word-complete-guide','api-security-complete-guide','data-masking-complete-guide',
'encryption-tools-complete-guide','firewall-tester-complete-guide','hash-generator-complete-guide','secure-file-wipe-complete-guide',
'security-analyzer-complete-guide','ssl-checker-complete-guide','two-factor-auth-complete-guide','case-converter-complete-guide',
'character-counter-complete-guide','cv-builder-complete-guide','lorem-ipsum-complete-guide','markdown-editor-complete-guide',
'regex-tester-complete-guide','text-diff-complete-guide','text-extractor-complete-guide','uuid-generator-complete-guide'
);

INSERT INTO blog_posts (title,slug,content,excerpt,category,lang,status,tool_slug,tool_name,seo_title,seo_description,seo_keywords,parent_slug,created_at,updated_at) VALUES
('JavaScript Formatter — Complete Guide 2026','javascript-formatter-complete-guide','<h2>📖 What is a JavaScript Formatter?</h2><p>A <strong>JavaScript Formatter</strong> beautifies and formats JS code with proper indentation for readability and debugging.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>⚡ Instant Formatting</li><li>📝 Proper Indentation</li><li>🆓 Free Forever</li></ul>','Free JavaScript Formatter guide. Beautify JS code instantly.','code-tools','en','published','javascript-formatter','JavaScript Formatter','Free JavaScript Formatter — Beautify JS Code | Centers.pk','Format JavaScript code with proper indentation. Free, private.','javascript formatter, js beautifier, format javascript','javascript-formatter-complete-guide',datetime('now'),datetime('now')),
('جاوا اسکرپٹ فارمیٹر — مکمل گائیڈ 2026','javascript-formatter-complete-guide','<h2>📖 جاوا اسکرپٹ فارمیٹر کیا ہے؟</h2><p><strong>جاوا اسکرپٹ فارمیٹر</strong> JS کوڈ کو خوبصورت بناتا ہے۔</p>','مفت جاوا اسکرپٹ فارمیٹر۔ JS کوڈ خوبصورت کریں۔','code-tools','ur','published','javascript-formatter','جاوا اسکرپٹ فارمیٹر','مفت جاوا اسکرپٹ فارمیٹر | Centers.pk','JS کوڈ فارمیٹ کریں۔ مفت۔','جاوا اسکرپٹ فارمیٹر','javascript-formatter-complete-guide',datetime('now'),datetime('now')),
('जावास्क्रिप्ट फ़ॉर्मेटर — गाइड 2026','javascript-formatter-complete-guide','<h2>📖 जावास्क्रिप्ट फ़ॉर्मेटर क्या है?</h2><p><strong>जावास्क्रिप्ट फ़ॉर्मेटर</strong> JS कोड को सुंदर बनाता है।</p>','मुफ्त JS फ़ॉर्मेटर। JS कोड सुंदर करें।','code-tools','hi','published','javascript-formatter','जावास्क्रिप्ट फ़ॉर्मेटर','मुफ्त जावास्क्रिप्ट फ़ॉर्मेटर | Centers.pk','JS कोड फ़ॉर्मेट करें।','जावास्क्रिप्ट फ़ॉर्मेटर','javascript-formatter-complete-guide',datetime('now'),datetime('now')),
('منسق JavaScript — الدليل 2026','javascript-formatter-complete-guide','<h2>📖 ما هو منسق JavaScript؟</h2><p><strong>منسق JavaScript</strong> يجمل كود JS.</p>','منسق JavaScript مجاني.','code-tools','ar','published','javascript-formatter','منسق JavaScript','منسق JavaScript مجاني | Centers.pk','نسق كود JS. مجاني.','منسق JavaScript','javascript-formatter-complete-guide',datetime('now'),datetime('now')),

('XML Formatter — Complete Guide 2026','xml-formatter-complete-guide','<h2>📖 What is an XML Formatter?</h2><p>An <strong>XML Formatter</strong> beautifies and validates XML documents with proper indentation.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>⚡ Instant Formatting</li><li>✅ Validation</li><li>🆓 Free Forever</li></ul>','Free XML Formatter guide. Beautify XML instantly.','code-tools','en','published','xml-formatter','XML Formatter','Free XML Formatter — Beautify XML | Centers.pk','Format XML documents. Free, private.','xml formatter, xml beautifier','xml-formatter-complete-guide',datetime('now'),datetime('now')),
('XML فارمیٹر — مکمل گائیڈ 2026','xml-formatter-complete-guide','<h2>📖 XML فارمیٹر کیا ہے؟</h2><p><strong>XML فارمیٹر</strong> XML دستاویزات کو خوبصورت بناتا ہے۔</p>','مفت XML فارمیٹر۔','code-tools','ur','published','xml-formatter','XML فارمیٹر','مفت XML فارمیٹر | Centers.pk','XML فارمیٹ کریں۔','XML فارمیٹر','xml-formatter-complete-guide',datetime('now'),datetime('now')),
('XML फ़ॉर्मेटर — गाइड 2026','xml-formatter-complete-guide','<h2>📖 XML फ़ॉर्मेटर क्या है?</h2><p><strong>XML फ़ॉर्मेटर</strong> XML दस्तावेज़ों को सुंदर बनाता है।</p>','मुफ्त XML फ़ॉर्मेटर।','code-tools','hi','published','xml-formatter','XML फ़ॉर्मेटर','मुफ्त XML फ़ॉर्मेटर | Centers.pk','XML फ़ॉर्मेट करें।','XML फ़ॉर्मेटर','xml-formatter-complete-guide',datetime('now'),datetime('now')),
('منسق XML — الدليل 2026','xml-formatter-complete-guide','<h2>📖 ما هو منسق XML؟</h2><p><strong>منسق XML</strong> يجمل مستندات XML.</p>','منسق XML مجاني.','code-tools','ar','published','xml-formatter','منسق XML','منسق XML مجاني | Centers.pk','نسق XML.','منسق XML','xml-formatter-complete-guide',datetime('now'),datetime('now'));

INSERT INTO blog_posts (title,slug,content,excerpt,category,lang,status,tool_slug,tool_name,seo_title,seo_description,seo_keywords,parent_slug,created_at,updated_at) VALUES
('URL Encoder — Complete Guide 2026','url-encoder-complete-guide','<h2>📖 What is a URL Encoder?</h2><p>A <strong>URL Encoder</strong> converts text into URL-safe format using percent-encoding. Essential for web developers.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>⚡ Instant Encoding</li><li>🔄 Encode & Decode</li><li>🆓 Free Forever</li></ul>','Free URL Encoder guide. Encode URLs safely.','code-tools','en','published','url-encoder','URL Encoder','Free URL Encoder — Encode URLs Online | Centers.pk','URL encode and decode text. Free, private.','url encoder, url decoder, percent encoding','url-encoder-complete-guide',datetime('now'),datetime('now')),
('URL انکوڈر — مکمل گائیڈ 2026','url-encoder-complete-guide','<h2>📖 URL انکوڈر کیا ہے؟</h2><p><strong>URL انکوڈر</strong> ٹیکسٹ کو URL سیف فارمیٹ میں تبدیل کرتا ہے۔</p>','مفت URL انکوڈر۔','code-tools','ur','published','url-encoder','URL انکوڈر','مفت URL انکوڈر | Centers.pk','URL انکوڈ کریں۔','URL انکوڈر','url-encoder-complete-guide',datetime('now'),datetime('now')),
('URL एनकोडर — गाइड 2026','url-encoder-complete-guide','<h2>📖 URL एनकोडर क्या है?</h2><p><strong>URL एनकोडर</strong> टेक्स्ट को URL-सुरक्षित प्रारूप में बदलता है।</p>','मुफ्त URL एनकोडर।','code-tools','hi','published','url-encoder','URL एनकोडर','मुफ्त URL एनकोडर | Centers.pk','URL एनकोड करें।','URL एनकोडर','url-encoder-complete-guide',datetime('now'),datetime('now')),
('مشفر URL — الدليل 2026','url-encoder-complete-guide','<h2>📖 ما هو مشفر URL؟</h2><p><strong>مشفر URL</strong> يحول النص إلى تنسيق آمن للـ URL.</p>','مشفر URL مجاني.','code-tools','ar','published','url-encoder','مشفر URL','مشفر URL مجاني | Centers.pk','شفر URL.','مشفر URL','url-encoder-complete-guide',datetime('now'),datetime('now')),

('Base64 Encoder — Complete Guide 2026','base64-encoder-complete-guide','<h2>📖 What is a Base64 Encoder?</h2><p>A <strong>Base64 Encoder</strong> converts binary data to ASCII text format. Essential for data transmission and storage.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>⚡ Instant Conversion</li><li>🔄 Encode & Decode</li><li>🆓 Free Forever</li></ul>','Free Base64 Encoder guide. Encode/decode Base64.','code-tools','en','published','base64-encoder','Base64 Encoder','Free Base64 Encoder — Encode/Decode Online | Centers.pk','Base64 encode and decode text. Free, private.','base64 encoder, base64 decoder, base64 converter','base64-encoder-complete-guide',datetime('now'),datetime('now')),
('Base64 انکوڈر — مکمل گائیڈ 2026','base64-encoder-complete-guide','<h2>📖 Base64 انکوڈر کیا ہے؟</h2><p><strong>Base64 انکوڈر</strong> بائنری ڈیٹا کو ASCII میں تبدیل کرتا ہے۔</p>','مفت Base64 انکوڈر۔','code-tools','ur','published','base64-encoder','Base64 انکوڈر','مفت Base64 انکوڈر | Centers.pk','Base64 انکوڈ/ڈیکوڈ کریں۔','Base64 انکوڈر','base64-encoder-complete-guide',datetime('now'),datetime('now')),
('Base64 एनकोडर — गाइड 2026','base64-encoder-complete-guide','<h2>📖 Base64 एनकोडर क्या है?</h2><p><strong>Base64 एनकोडर</strong> बाइनरी डेटा को ASCII में बदलता है।</p>','मुफ्त Base64 एनकोडर।','code-tools','hi','published','base64-encoder','Base64 एनकोडर','मुफ्त Base64 एनकोडर | Centers.pk','Base64 एनकोड/डिकोड करें।','Base64 एनकोडर','base64-encoder-complete-guide',datetime('now'),datetime('now')),
('مشفر Base64 — الدليل 2026','base64-encoder-complete-guide','<h2>📖 ما هو مشفر Base64؟</h2><p><strong>مشفر Base64</strong> يحول البيانات الثنائية إلى ASCII.</p>','مشفر Base64 مجاني.','code-tools','ar','published','base64-encoder','مشفر Base64','مشفر Base64 مجاني | Centers.pk','شفر Base64.','مشفر Base64','base64-encoder-complete-guide',datetime('now'),datetime('now'));

INSERT INTO blog_posts (title,slug,content,excerpt,category,lang,status,tool_slug,tool_name,seo_title,seo_description,seo_keywords,parent_slug,created_at,updated_at) VALUES
('Color Picker — Complete Guide 2026','color-picker-complete-guide','<h2>📖 What is a Color Picker?</h2><p>A <strong>Color Picker</strong> helps you select, convert, and analyze colors in HEX, RGB, HSL, CMYK formats. Essential for designers and developers.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>🎨 Multiple Formats</li><li>👁️ Accessibility Checker</li><li>🆓 Free Forever</li></ul>','Free Color Picker guide. Pick and convert colors.','design-tools','en','published','color-picker','Color Picker','Free Color Picker — HEX RGB HSL Converter | Centers.pk','Pick colors, convert formats, check accessibility. Free.','color picker, hex to rgb, color converter','color-picker-complete-guide',datetime('now'),datetime('now')),
('رنگ چننے والا — مکمل گائیڈ 2026','color-picker-complete-guide','<h2>📖 رنگ چننے والا کیا ہے؟</h2><p><strong>رنگ چننے والا</strong> HEX RGB HSL CMYK میں رنگ منتخب کرتا ہے۔</p>','مفت رنگ چننے والا۔','design-tools','ur','published','color-picker','رنگ چننے والا','مفت رنگ چننے والا | Centers.pk','رنگ منتخب کریں، فارمیٹ تبدیل کریں۔','رنگ چننے والا','color-picker-complete-guide',datetime('now'),datetime('now')),
('रंग चुनने वाला — गाइड 2026','color-picker-complete-guide','<h2>📖 रंग चुनने वाला क्या है?</h2><p><strong>रंग चुनने वाला</strong> HEX RGB HSL CMYK में रंग चुनता है।</p>','मुफ्त रंग चुनने वाला।','design-tools','hi','published','color-picker','रंग चुनने वाला','मुफ्त रंग चुनने वाला | Centers.pk','रंग चुनें, फॉर्मेट बदलें।','रंग चुनने वाला','color-picker-complete-guide',datetime('now'),datetime('now')),
('منتقي الألوان — الدليل 2026','color-picker-complete-guide','<h2>📖 ما هو منتقي الألوان؟</h2><p><strong>منتقي الألوان</strong> يختار الألوان بصيغ HEX RGB HSL CMYK.</p>','منتقي ألوان مجاني.','design-tools','ar','published','color-picker','منتقي الألوان','منتقي ألوان مجاني | Centers.pk','اختر الألوان، حول الصيغ.','منتقي الألوان','color-picker-complete-guide',datetime('now'),datetime('now'));

INSERT INTO blog_posts (title,slug,content,excerpt,category,lang,status,tool_slug,tool_name,seo_title,seo_description,seo_keywords,parent_slug,created_at,updated_at) VALUES
('Background Remover — Complete Guide 2026','background-remover-complete-guide','<h2>📖 What is a Background Remover?</h2><p>A <strong>Background Remover</strong> removes image backgrounds automatically using AI. Essential for e-commerce, designers, and photographers.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>🤖 AI-Powered</li><li>⚡ Instant Results</li><li>🆓 Free Forever</li></ul>','Free Background Remover guide. Remove image backgrounds with AI.','image-tools','en','published','background-remover','Background Remover','Free Background Remover — Remove Image Background | Centers.pk','AI-powered background removal. Free, private, no upload.','background remover, remove bg, ai background remover','background-remover-complete-guide',datetime('now'),datetime('now')),
('بیک گراؤنڈ ہٹانے والا — گائیڈ 2026','background-remover-complete-guide','<h2>📖 بیک گراؤنڈ ہٹانے والا کیا ہے؟</h2><p><strong>بیک گراؤنڈ ہٹانے والا</strong> AI سے تصویر کا بیک گراؤنڈ ہٹاتا ہے۔</p>','مفت بیک گراؤنڈ ہٹانے والا۔','image-tools','ur','published','background-remover','بیک گراؤنڈ ہٹانے والا','مفت بیک گراؤنڈ ہٹانے والا | Centers.pk','AI سے بیک گراؤنڈ ہٹائیں۔','بیک گراؤنڈ ہٹانے والا','background-remover-complete-guide',datetime('now'),datetime('now')),
('बैकग्राउंड रिमूवर — गाइड 2026','background-remover-complete-guide','<h2>📖 बैकग्राउंड रिमूवर क्या है?</h2><p><strong>बैकग्राउंड रिमूवर</strong> AI से इमेज बैकग्राउंड हटाता है।</p>','मुफ्त बैकग्राउंड रिमूवर।','image-tools','hi','published','background-remover','बैकग्राउंड रिमूवर','मुफ्त बैकग्राउंड रिमूवर | Centers.pk','AI से बैकग्राउंड हटाएं।','बैकग्राउंड रिमूवर','background-remover-complete-guide',datetime('now'),datetime('now')),
('مزيل الخلفية — الدليل 2026','background-remover-complete-guide','<h2>📖 ما هو مزيل الخلفية؟</h2><p><strong>مزيل الخلفية</strong> يزيل خلفيات الصور بالذكاء الاصطناعي.</p>','مزيل خلفية مجاني.','image-tools','ar','published','background-remover','مزيل الخلفية','مزيل خلفية مجاني | Centers.pk','أزل الخلفية بالذكاء الاصطناعي.','مزيل الخلفية','background-remover-complete-guide',datetime('now'),datetime('now'));

INSERT INTO blog_posts (title,slug,content,excerpt,category,lang,status,tool_slug,tool_name,seo_title,seo_description,seo_keywords,parent_slug,created_at,updated_at) VALUES
('Favicon Generator — Complete Guide 2026','favicon-generator-complete-guide','<h2>📖 What is a Favicon Generator?</h2><p>A <strong>Favicon Generator</strong> creates website favicons from any image. Essential for web developers and site owners.</p><h2>🌟 Why Choose Centers.pk?</h2><ul><li>🔒 100% Private</li><li>🖼️ Multiple Sizes</li><li>⚡ Instant Generation</li><li>🆓 Free Forever</li></ul>','Free Favicon Generator guide. Create favicons instantly.','image-tools','en','published','favicon-generator','Favicon Generator','Free Favicon Generator — Create Website Icons | Centers.pk','Generate favicons from any image. Free, private.','favicon generator, favicon maker, website icon','favicon-generator-complete-guide',datetime('now'),datetime('now')),
('فیویکون جنریٹر — گائیڈ 2026','favicon-generator-complete-guide','<h2>📖 فیویکون جنریٹر کیا ہے؟</h2><p><strong>فیویکون جنریٹر</strong> ویب سائٹ کے لیے فیویکون بناتا ہے۔</p>','مفت فیویکون جنریٹر۔','image-tools','ur','published','favicon-generator','فیویکون جنریٹر','مفت فیویکون جنریٹر | Centers.pk','فیویکون بنائیں۔','فیویکون جنریٹر','favicon-generator-complete-guide',datetime('now'),datetime('now')),
('फेविकॉन जनरेटर — गाइड 2026','favicon-generator-complete-guide','<h2>📖 फेविकॉन जनरेटर क्या है?</h2><p><strong>फेविकॉन जनरेटर</strong> वेबसाइट के लिए फेविकॉन बनाता है।</p>','मुफ्त फेविकॉन जनरेटर।','image-tools','hi','published','favicon-generator','फेविकॉन जनरेटर','मुफ्त फेविकॉन जनरेटर | Centers.pk','फेविकॉन बनाएं।','फेविकॉन जनरेटर','favicon-generator-complete-guide',datetime('now'),datetime('now')),
('مولد الأيقونات — الدليل 2026','favicon-generator-complete-guide','<h2>📖 ما هو مولد الأيقونات؟</h2><p><strong>مولد الأيقونات</strong> ينشئ أيقونات المواقع.</p>','مولد أيقونات مجاني.','image-tools','ar','published','favicon-generator','مولد الأيقونات','مولد أيقونات مجاني | Centers.pk','أنشئ أيقونات.','مولد الأيقونات','favicon-generator-complete-guide',datetime('now'),datetime('now'));
