export const PricingContent = {
  title: "اختر خطتك",
  subtitle: "افتح الميزات المميزة وعزز تجربتك",
  monthly: "شهري",
  yearly: "سنوي",
  save: "وفر 17%",
  free: "مجاني",
  pro: "برو",
  premium: "مميز",
  lifetime: "مدى الحياة",
  most_popular: "الأكثر شعبية",
  best_value: "أفضل قيمة",
  get_started: "ابدأ مجاناً",
  go_pro: "احصل على برو",
  go_premium: "احصل على المميزة",
  get_lifetime: "احصل على مدى الحياة",
  selected: "محدد ✓",
  per_month: "/شهر",
  per_year: "/سنة",
  one_time: "مرة واحدة",
  features: "الميزات",
  enterprise_title: "تحتاج شيئاً مخصصاً؟",
  enterprise_desc: "اتصل بنا للتسعير المؤسسي والخصومات.",
  contact_sales: "اتصل بالمبيعات →",
  complete_payment: "أكمل الدفع",
  select_method: "اختر طريقة الدفع:",
  send_to: "أرسل الدفع إلى:",
  your_name: "اسمك",
  transaction_id: "رقم المعاملة / المرجع",
  submit_payment: "تقديم الدفع",
  submitting: "جاري التقديم...",
  payment_submitted: "تم تقديم الدفع!",
  payment_verifying: "يتم التحقق من دفعتك. ستتلقى الوصول خلال 24 ساعة.",
  verified_24h: "⚡ يتم التحقق من المدفوعات خلال 24 ساعة",
};
