export const PricingContent = {
  title: "Choose Your Plan",
  subtitle: "Unlock premium features and supercharge your experience",
  monthly: "Monthly",
  yearly: "Yearly",
  save: "Save 17%",
  free: "Free",
  pro: "Pro",
  premium: "Premium",
  lifetime: "Lifetime",
  most_popular: "MOST POPULAR",
  best_value: "BEST VALUE",
  get_started: "Get Started Free",
  go_pro: "Go Pro",
  go_premium: "Go Premium",
  get_lifetime: "Get Lifetime",
  selected: "Selected ✓",
  per_month: "/mo",
  per_year: "/yr",
  one_time: "one-time",
  features: "Features",
  enterprise_title: "Need something custom?",
  enterprise_desc: "Contact us for enterprise pricing, bulk discounts, or white-label solutions.",
  contact_sales: "Contact Sales →",
  complete_payment: "Complete Payment",
  select_method: "Select Payment Method:",
  send_to: "Send Payment To:",
  your_name: "Your Name",
  transaction_id: "Transaction ID / Reference",
  submit_payment: "Submit Payment",
  submitting: "Submitting...",
  payment_submitted: "Payment Submitted!",
  payment_verifying: "Your payment is being verified. You'll receive access within 24 hours.",
  verified_24h: "⚡ Payments verified within 24 hours",
};
