export const PricingContent = {
  title: "अपना प्लान चुनें",
  subtitle: "प्रीमियम सुविधाएं अनलॉक करें",
  monthly: "मासिक",
  yearly: "वार्षिक",
  save: "17% बचाएं",
  free: "मुफ्त",
  pro: "प्रो",
  premium: "प्रीमियम",
  lifetime: "लाइफटाइम",
  most_popular: "सबसे लोकप्रिय",
  best_value: "सर्वोत्तम मूल्य",
  get_started: "मुफ्त शुरू करें",
  go_pro: "प्रो बनें",
  go_premium: "प्रीमियम बनें",
  get_lifetime: "लाइफटाइम लें",
  selected: "चयनित ✓",
  per_month: "/माह",
  per_year: "/वर्ष",
  one_time: "एक बार",
  features: "सुविधाएं",
  enterprise_title: "कुछ विशेष चाहिए?",
  enterprise_desc: "एंटरप्राइज मूल्य निर्धारण के लिए संपर्क करें।",
  contact_sales: "सेल्स से संपर्क करें →",
  complete_payment: "भुगतान पूरा करें",
  select_method: "भुगतान विधि चुनें:",
  send_to: "भुगतान भेजें:",
  your_name: "आपका नाम",
  transaction_id: "लेन-देन ID / संदर्भ",
  submit_payment: "भुगतान जमा करें",
  submitting: "जमा हो रहा है...",
  payment_submitted: "भुगतान जमा हो गया!",
  payment_verifying: "आपके भुगतान की पुष्टि हो रही है। 24 घंटे में एक्सेस मिलेगा।",
  verified_24h: "⚡ भुगतान 24 घंटे में सत्यापित",
};
