export const PricingContent = {
  title: "اپنا پلان منتخب کریں",
  subtitle: "پریمیم فیچرز کو غیر مقفل کریں",
  monthly: "ماہانہ",
  yearly: "سالانہ",
  save: "17% بچائیں",
  free: "مفت",
  pro: "پرو",
  premium: "پریمیم",
  lifetime: "لائف ٹائم",
  most_popular: "سب سے مقبول",
  best_value: "بہترین قیمت",
  get_started: "مفت شروع کریں",
  go_pro: "پرو بنیں",
  go_premium: "پریمیم بنیں",
  get_lifetime: "لائف ٹائم حاصل کریں",
  selected: "منتخب ✓",
  per_month: "/ماہ",
  per_year: "/سال",
  one_time: "یک بار",
  features: "خصوصیات",
  enterprise_title: "کچھ خاص چاہیے؟",
  enterprise_desc: "انٹرپرائز قیمتوں، بلک ڈسکاؤنٹ کے لیے رابطہ کریں۔",
  contact_sales: "سیلز سے رابطہ کریں →",
  complete_payment: "ادائیگی مکمل کریں",
  select_method: "ادائیگی کا طریقہ منتخب کریں:",
  send_to: "ادائیگی بھیجیں:",
  your_name: "آپ کا نام",
  transaction_id: "ٹرانزیکشن ID / حوالہ",
  submit_payment: "ادائیگی جمع کروائیں",
  submitting: "جمع کروایا جا رہا ہے...",
  payment_submitted: "ادائیگی جمع کروا دی گئی!",
  payment_verifying: "آپ کی ادائیگی کی تصدیق ہو رہی ہے۔ 24 گھنٹے میں رسائی مل جائے گی۔",
  verified_24h: "⚡ ادائیگیاں 24 گھنٹے میں تصدیق شدہ",
};
