'use client';
import { useContext, useState } from 'react';
import { CVContext } from '../tool.client';
import { Download, Share2, FileText, Copy, Printer, Loader2 } from 'lucide-react';
import { useTheme } from '@/components/theme';

export default function ExportOptions() {
  const { state } = useContext(CVContext);
  const { themeColors } = useTheme();
  const [isExporting, setIsExporting] = useState(false);
  const [showShareUrl, setShowShareUrl] = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [copied, setCopied] = useState(false);

  const exportPDF = async () => {
    setIsExporting(true);
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      canvas.width = 794; // A4
      canvas.height = 1123;
      if (ctx) {
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.fillStyle = '#000000';
        ctx.font = '20px Arial';
        ctx.fillText((state.personalInfo as any)?.name || 'Your Name', 50, 80);
        ctx.font = '14px Arial';
        ctx.fillText((state.summary as string)?.substring(0, 500) || '', 50, 120, 700);
        ctx.fillText('Generated by Centre.com.pk — Free CV Builder', 50, 1100);
      }
      const link = document.createElement('a');
      link.download = 'my-cv.pdf';
      link.href = canvas.toDataURL('image/pdf');
      document.body.appendChild(link); link.click(); document.body.removeChild(link);
    } catch (e) { alert('PDF export failed. Try Print (Ctrl+P) instead.'); }
    setIsExporting(false);
  };

  const createShareLink = async () => {
    try {
      const res = await fetch('/api/token/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'cv-card', cardData: state, sections: {}, customization: {} }),
      });
      const data = await res.json();
      if (data.success) { setShareUrl(data.url); setShowShareUrl(true); }
    } catch (e) { alert('Share link creation failed'); }
  };

  const copyLink = async () => {
    await navigator.clipboard.writeText(shareUrl);
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3 p-4 rounded-xl border" style={{ backgroundColor: themeColors.surface, borderColor: themeColors.border }}>
      <h3 className="text-lg font-semibold flex items-center gap-2" style={{ color: themeColors.text.primary }}>
        <Download className="w-5 h-5" style={{ color: themeColors.primary }} />Export & Share
      </h3>
      
      <div className="grid grid-cols-2 gap-2">
        <button onClick={exportPDF} disabled={isExporting}
          className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-lg text-white text-xs font-semibold disabled:opacity-50"
          style={{ backgroundColor: themeColors.primary }}>
          {isExporting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
          PDF
        </button>
        <button onClick={() => window.print()}
          className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-lg border text-xs font-semibold"
          style={{ borderColor: themeColors.border, color: themeColors.text.primary }}>
          <Printer className="w-3.5 h-3.5" /> Print
        </button>
        <button onClick={createShareLink}
          className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-lg border text-xs font-semibold"
          style={{ borderColor: themeColors.border, color: themeColors.text.primary }}>
          <Share2 className="w-3.5 h-3.5" /> Share
        </button>
        <button onClick={() => navigator.clipboard.writeText(JSON.stringify(state, null, 2))}
          className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-lg border text-xs font-semibold"
          style={{ borderColor: themeColors.border, color: themeColors.text.primary }}>
          <Copy className="w-3.5 h-3.5" /> Copy Data
        </button>
      </div>

      {showShareUrl && (
        <div className="p-2 rounded-lg border border-green-200 bg-green-50">
          <p className="text-xs text-green-700 mb-1">✅ Share Link Ready!</p>
          <div className="flex gap-1">
            <input readOnly value={shareUrl} className="flex-1 px-2 py-1 text-xs rounded border" />
            <button onClick={copyLink} className="px-2 py-1 text-xs rounded bg-green-500 text-white">
              {copied ? '✓' : 'Copy'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
